import os
import secrets
import sys
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"


def _is_windows() -> bool:
    return os.name == "nt"


def _default_backup_dir() -> str:
    if _is_windows():
        return str(Path.home() / "Documents" / "PerFinPyBackups")
    return str(Path.home() / "PerFinPyBackups")


def _prompt(label: str, default: str | None = None, *, secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        if secret:
            import getpass

            value = getpass.getpass(f"{label}{suffix}: ").strip()
        else:
            value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        print("Value required.", file=sys.stderr)


def _prompt_int(label: str, default: int) -> int:
    while True:
        raw = _prompt(label, str(default))
        try:
            value = int(raw)
            if value < 0:
                raise ValueError
            return value
        except ValueError:
            print("Enter a non-negative integer.", file=sys.stderr)


def _normalize_export_url(value: str) -> str:
    value = value.strip()
    if not value:
        return ""

    parsed = urlparse(value)
    if not parsed.scheme:
        value = "http://" + value
        parsed = urlparse(value)
    if parsed.scheme not in ("http", "https"):
        raise ValueError("Export URL must start with http:// or https://")
    if not parsed.netloc:
        raise ValueError("Export URL must include host:port (e.g. http://pf-app:5173)")

    if parsed.path in ("", "/"):
        return value.rstrip("/") + "/api/transactions/export?period=all"
    if parsed.path == "/api/transactions/export":
        return value + ("?period=all" if not parsed.query else "")
    return value


def _confirm_overwrite(path: Path) -> None:
    if not path.exists():
        return
    ans = _prompt(f"{path.name} already exists. Overwrite? (y/N)", "N")
    if ans.lower() not in ("y", "yes"):
        print("Cancelled.", file=sys.stderr)
        raise SystemExit(1)


def main() -> int:
    print("PerFinPy setup wizard")
    print("---------------------")
    print("This will create/update a local .env file (it is gitignored).")
    print("")

    _confirm_overwrite(ENV_PATH)

    database_url = _prompt("DATABASE_URL", "sqlite:///accounting.db")
    secret_key = _prompt("SECRET_KEY (leave blank to auto-generate)", default="")
    if not secret_key:
        secret_key = secrets.token_urlsafe(48)

    backup_dir = _prompt("PERFINPY_BACKUP_DIR", _default_backup_dir())
    keep_latest = _prompt_int("PERFINPY_BACKUP_KEEP_LATEST", 5)

    export_url_raw = _prompt(
        "PERFINPY_EXPORT_URL (Oracle/Tailscale base URL; blank = local export)",
        "http://pf-app:5173",
    )
    try:
        export_url = _normalize_export_url(export_url_raw)
    except ValueError as exc:
        print(f"Invalid PERFINPY_EXPORT_URL: {exc}", file=sys.stderr)
        return 2

    export_retries = _prompt_int("PERFINPY_EXPORT_RETRIES", 12)
    export_retry_delay = _prompt_int("PERFINPY_EXPORT_RETRY_DELAY", 10)

    lines: list[str] = []
    lines.append("# Local environment for PerFinPy")
    lines.append("# Generated by install-wizard.py; safe to edit.")
    lines.append("")
    lines.append(f"DATABASE_URL={database_url}")
    lines.append(f"SECRET_KEY={secret_key}")
    lines.append("")
    lines.append("# Excel backup/export")
    lines.append(f"PERFINPY_BACKUP_DIR={backup_dir}")
    lines.append(f"PERFINPY_BACKUP_KEEP_LATEST={keep_latest}")
    lines.append(f"PERFINPY_EXPORT_URL={export_url}")
    lines.append(f"PERFINPY_EXPORT_RETRIES={export_retries}")
    lines.append(f"PERFINPY_EXPORT_RETRY_DELAY={export_retry_delay}")
    lines.append("")

    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")

    print("")
    print(f"Wrote {ENV_PATH}")
    print("Next:")
    if _is_windows():
        print("  - Run dev.cmd (dev) or prod.cmd (production-style).")
        print("  - If you use the logon export task, run install-windows-startup-export-task.ps1 again.")
    else:
        print("  - Run ./prod.sh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

